DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    first VARCHAR(100),
    last VARCHAR(100),
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(200) NOT NULL,
    image TEXT,
    bio TEXT
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
